[ch24980]Make Financial Findings editable
unicef/etools-auditor-portal pull request #415
Opened 2021-02-18 16:13 UTC by acory

[ch24980]

2021-02-18 16:14 UTC, acory commented
NOTE :  BK is not saving the fields

2021-02-19 09:00 UTC, danNordlogic approved these changes

2021-02-26 15:56 UTC, robertavram requested changes

2021-02-26 15:56 UTC, robertavram commented on src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts
> -              readonly$="{{isReadOnly('explanation_for_additional_information', basePermissionPath)}}"
we've updated all the permissions from the backend. the only issue remains that the save button is not available. so we no longer need the changes here.. but whatever is keeping the save button from showing up should be changed.. I assume it has something to do with the status.

2021-02-26 15:56 UTC, robertavram commented on src_ts/elements/common-elements/status-tab-element/status-tab-element.ts
> +    const actions = permissionBase ? getActions(permissionBase) : [];
i guess this will fix what i mentioned earlier about the save button? :)

2021-03-01 15:03 UTC, merged